### ISSUE TITLE
unfortunately not working with netbox 3.3.5

### ISSUE THREAD

**Issue by geaclaesson** [dainok/netdoc#15]
I couldn't get this to work with netbox 3.3.5. Using Ubuntu 20.4 and Python 3.10.4.

It halted with django storages distribute_setup.

**Comment by dainok** [comment]
Can you attach the error?

**Comment by geaclaesson** [comment]
I should mention it is an install on an already running Netbox server, not from scratch. (with Python 3.10.6).

![image](https://user-images.githubusercontent.com/44589816/203325602-c18b2051-c8f2-4da2-a25f-8946948e47ab.png)

I managed to bypass some of it by updating the requirements txt since I already had some of them. 

This part failed after that:
./manage.py shell < set_interface_shortname.django

But the plugin is up and running, I added a username and discoverable, however, it does not seem to go to the next node, only 
the node added as discoverable. Is that expected behavior?

**Comment by dainok** [comment]
Yes, currently discovery stops after first discovery because user should update credentials and type. In the future netdoc could guess them, but not now.

I don't get if you fixed the issue or not. And, honestly, I didn't understand details about the issue. The error is complaining about a missing distribute_setup module, it's cause by django/netbox not netdoc.

**Comment by geaclaesson** [comment]
Mea culpa, I thought the django install/update was a part of the netdoc install and the set_interface_shortname.django was crucial to the setup process.

I've frankensteined this netbox setup I think,  but I got your plugin up and running. I am beyond grateful. 

THANK YOU!

**Comment by dainok** [comment]
No worries.
