### ISSUE TITLE
[Issue] Nornir / netmiko.

### ISSUE THREAD

**Issue by deku-m** [dainok/netdoc#19]
Hi,
I am not sure if this is a issue regarding your plugin but lets see.
The following is happening when deploying it in docker container.

See below.
![afbeelding](https://user-images.githubusercontent.com/37069737/207560113-3af89b33-1932-40e9-921a-b74211ce2dd0.png)

I saw in your setup.py that you are still using 0.1.2
`install_requires=['python-slugify', 'nornir==3.3.0', 'nornir_utils==0.2.0', **'nornir_netmiko==0.1.2',** 'ipaddress', 'macaddress', 'ouilookup'],`

When looking on the plugin page it is mentioning 0.2.0:
https://github.com/ktbyers/nornir_netmiko

Is this because of the underlaying plugin is replaced by older version?

**Comment by dainok** [comment]
Mmmm I don't get why it's trying to install netmiko 4.0 even if I'm using an old version of nornir_netmiko.
The reason why I'm forcing an old release is that major versions usually break a lot of things.

Can you run a couple of tests?

1. force an old 3.x.y netmiko version and check if netdoc install fine
2. try to use an updated version of nornir_netmiko and check if netdock is still working

Otherwise I can do that, but it will require a few because I'm very busy in the next weeks.

**Comment by deku-m** [comment]
No it is installing the old version i guess.. because i could install your plugin and netbox is running but might break in future with the rest maybe. And i thought with 0.2.0 from nornir_netmiko it was saying version 4.x was supported.

**Comment by dainok** [comment]
@deku-m can you test this branch?

https://github.com/dainok/netdoc/tree/update_nornir

Unfortunately I don't have a full test env right now.

**Comment by deku-m** [comment]
Thanks.

I wonder how i can test this in docker as i don't really pull the repo anywhere.
Or i need to make a new linux setup with installed but that i can later this week.
