### ISSUE TITLE
Feature: Compatibility with Nautobot ? 

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#60]
Hi,

have you thought about possibility of adapting Netdoc to be compatible with Nautobot API also? [https://github.com/nautobot/nautobot](url)

**Comment by dainok** [comment]
When I started NetDoc as plugin, I started with Nautobot. I had very strange issues, and the same code worked with NetBox. That's why I'm using NetBox.
Maintaining a compatibility between NetBox versions AND Nautobot versions is a very time consuming task. Feel free to contribute :)
I still have to upgrade NetDoc to be compatibile with NetBox v3.5.

**Comment by dainok** [comment]
@svestenik I get the curiosity to see what NTC is doing, and I found that Nautobot has grown a lot.
Are you using Nautobot? Have you tested https://networktocode.com/apps/device-onboarding/ ? It seems similar to NetDoc.
